services:
  update-server:
    build: .
    container_name: update-server
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - UPLOAD_DIR=/app/uploads
      - MYSQL_HOST=mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.common-server.rule=Host(`api.wkaiys.top`)"
      - "traefik.http.routers.common-server.entrypoints=websecure"
      - "traefik.http.routers.common-server.tls.certresolver=myresolver"
      - "traefik.http.services.common-server.loadbalancer.server.port=3600"
      - "traefik.http.routers.common-server-http.rule=Host(`api.wkaiys.top`)"
      - "traefik.http.routers.common-server-http.entrypoints=web"
      - "traefik.http.routers.common-server-http.middlewares=common-server-redirect"
      - "traefik.http.middlewares.common-server-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.common-server-redirect.redirectscheme.permanent=true"
    volumes:
      - /data/common-server/uploads:/app/uploads
    networks:
      - gateway-network
      - infra-network

networks:
  gateway-network:
    external: true
  infra-network:
    external: true
